[
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: invoices\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.invoices (\n  client_phone text NOT NULL,\n  client_name text NOT NULL,\n  id bigint NOT NULL,\n  id_status bigint NOT NULL,\n  created_at timestamp with time zone NOT NULL,\n  paid boolean NOT NULL,\n  invoice_date timestamp with time zone NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: maintenance\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.maintenance (\n  value1 character varying,\n  value2 character varying,\n  status_id bigint,\n  created_at timestamp with time zone NOT NULL,\n  id bigint NOT NULL,\n  name character varying NOT NULL,\n  value3 character varying\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: order_items\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.order_items (\n  created_at timestamp with time zone NOT NULL,\n  client_name text NOT NULL,\n  client_phone text NOT NULL,\n  image_url text,\n  id bigint NOT NULL,\n  size text,\n  product_name text NOT NULL,\n  quantity integer,\n  price numeric NOT NULL,\n  usa_reviewed boolean NOT NULL,\n  id_status bigint NOT NULL,\n  invoice_id bigint\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: payments\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.payments (\n  payment_date timestamp with time zone NOT NULL,\n  amount numeric NOT NULL,\n  created_at timestamp with time zone NOT NULL,\n  reference_code text,\n  id bigint NOT NULL,\n  invoice_id bigint NOT NULL,\n  payment_method text,\n  notes text,\n  bank_reviewed boolean NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: product_category\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.product_category (\n  id_status bigint,\n  id_category bigint NOT NULL,\n  category_name character varying(100) NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: product_status\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.product_status (\n  created_at timestamp with time zone,\n  status_name text NOT NULL,\n  id_product_status bigint NOT NULL,\n  is_available boolean NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: products\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.products (\n  product_name text NOT NULL,\n  id_product bigint NOT NULL,\n  price numeric NOT NULL,\n  id_product_status bigint NOT NULL,\n  id_status bigint NOT NULL,\n  created_at timestamp with time zone,\n  category bigint,\n  size text,\n  image_url text NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: status\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.status (\n  disabled boolean NOT NULL,\n  status_name character varying(50) NOT NULL,\n  id_status bigint NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: status_tracking\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.status_tracking (\n  id_status bigint NOT NULL,\n  id_status_tracking bigint NOT NULL,\n  status_name character varying(100) NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: stores\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.stores (\n  id_status bigint NOT NULL,\n  tienda_code text NOT NULL,\n  created_at timestamp with time zone,\n  nombre_tienda text NOT NULL,\n  id_store bigint NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: tracking\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.tracking (\n  cliente character varying(150) NOT NULL,\n  codigo_seguimiento_interno character varying(100) NOT NULL,\n  fecha_entrega_miami date,\n  fecha_compra date NOT NULL,\n  id_tracking bigint NOT NULL,\n  id_store bigint,\n  producto character varying(150) NOT NULL,\n  codigo_seguimiento_externo character varying(100)\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: tracking_historial\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.tracking_historial (\n  id_status_tracking bigint NOT NULL,\n  id_tracking bigint NOT NULL,\n  id bigint NOT NULL,\n  detalle text,\n  fecha_hora timestamp with time zone NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- TABLA: users\n-- ==========================================\nCREATE TABLE IF NOT EXISTS public.users (\n  id bigint NOT NULL,\n  created_at timestamp with time zone NOT NULL,\n  id_status bigint NOT NULL,\n  User_Name character varying NOT NULL,\n  User character varying NOT NULL,\n  Contraseña text NOT NULL\n);\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_tracking_historial_by_guia\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_tracking_historial_by_guia(p_numero_guia text)\n RETURNS TABLE(fecha_hora timestamp with time zone, detalle_estado text, nota text)\n LANGUAGE sql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\n    SELECT\r\n        th.fecha_hora,\r\n        st.status_name AS detalle_estado,\r\n        th.detalle AS nota\r\n    FROM tracking_historial th\r\n    JOIN tracking t ON th.id_tracking = t.id_tracking\r\n    JOIN status_tracking st ON th.id_status_tracking = st.id_status_tracking\r\n    WHERE t.codigo_seguimiento_interno = p_numero_guia\r\n       OR t.codigo_seguimiento_externo = p_numero_guia\r\n    ORDER BY th.fecha_hora ASC;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: search_products\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.search_products(p_search text)\n RETURNS TABLE(id_product bigint, product_name text, category text, size text, price numeric, image_url text, product_status text)\n LANGUAGE sql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\n  SELECT\r\n    p.id_product,\r\n    p.product_name,\r\n    p.category,\r\n    p.size,\r\n    p.price,\r\n    p.image_url,\r\n    ps.status_name\r\n  FROM products p\r\n  JOIN product_status ps ON p.id_product_status = ps.id_product_status\r\n  WHERE p.product_name ILIKE '%' || p_search || '%'\r\n     OR p.category ILIKE '%' || p_search || '%'\r\n  ORDER BY p.created_at DESC;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_invoice_summary\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_invoice_summary(p_invoice_id bigint)\n RETURNS TABLE(tipo_registro text, descripcion_o_producto text, foto text, cantidad integer, precio_unitario numeric, monto_total numeric, fecha timestamp with time zone)\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nBEGIN\r\n  RETURN QUERY\r\n  \r\n  -- 1. Detalle de Ítems / Productos\r\n  SELECT \r\n    'ITEM'::text AS tipo_registro,\r\n    oi.product_name AS descripcion_o_producto,\r\n    oi.image_url AS foto,\r\n    oi.quantity AS cantidad,\r\n    oi.price AS precio_unitario,\r\n    (oi.price * oi.quantity) AS monto_total,\r\n    i.invoice_date AS fecha\r\n  FROM invoices i\r\n  JOIN order_items oi ON i.id = oi.invoice_id\r\n  WHERE i.id = p_invoice_id\r\n\r\n  UNION ALL\r\n\r\n  -- 2. Detalle de Abonos / Pagos\r\n  SELECT \r\n    'PAYMENT'::text AS tipo_registro,\r\n    COALESCE(p.payment_method, 'Abono') || \r\n      CASE \r\n        WHEN p.reference_code IS NOT NULL AND p.reference_code != '' \r\n        THEN ' (Ref: ' || p.reference_code || ')' \r\n        ELSE '' \r\n      END AS descripcion_o_producto,\r\n    NULL::text AS foto,\r\n    1 AS cantidad,\r\n    p.amount AS precio_unitario,\r\n    p.amount AS monto_total,\r\n    p.payment_date AS fecha\r\n  FROM invoices i\r\n  JOIN payments p ON i.id = p.invoice_id\r\n  WHERE i.id = p_invoice_id\r\n\r\n  ORDER BY tipo_registro DESC, fecha ASC;\r\nEND;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_admin_invoices\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_admin_invoices()\n RETURNS TABLE(id bigint, client_name text, client_phone text, invoice_date timestamp with time zone, id_status bigint, status_name character varying, items_count text, paid boolean)\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nBEGIN\r\n  RETURN QUERY\r\n  SELECT \r\n    public.invoices.id,\r\n    public.invoices.client_name,\r\n    public.invoices.client_phone,\r\n    public.invoices.invoice_date,\r\n    public.invoices.id_status,\r\n    COALESCE(s.status_name, 'N/A') AS status_name,\r\n    'O: ' || COALESCE(o.total_items, 0)::text || ' P: ' || COALESCE(p.total_payments, 0)::text AS items_count,\r\n    public.invoices.paid\r\n  FROM public.invoices\r\n  LEFT JOIN public.status s \r\n    ON public.invoices.id_status = s.id_status\r\n  LEFT JOIN (\r\n    SELECT \r\n      order_items.invoice_id, \r\n      SUM(order_items.quantity)::bigint AS total_items -- O COUNT(order_items.id) si prefieres contar registros\r\n    FROM public.order_items\r\n    GROUP BY order_items.invoice_id\r\n  ) o ON public.invoices.id = o.invoice_id\r\n  LEFT JOIN (\r\n    SELECT \r\n      payments.invoice_id, \r\n      COUNT(payments.id) AS total_payments\r\n    FROM public.payments\r\n    GROUP BY payments.invoice_id\r\n  ) p ON public.invoices.id = p.invoice_id\r\n  ORDER BY public.invoices.id DESC;\r\nEND;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_public_catalog_products\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_public_catalog_products()\n RETURNS TABLE(id_product bigint, product_name text, category bigint, size text, price numeric, image_url text, is_available boolean, status_name text)\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nBEGIN\r\n    RETURN QUERY\r\n    SELECT\r\n        p.id_product,\r\n        p.product_name,\r\n        p.category,\r\n        p.size,\r\n        p.price,\r\n        p.image_url,\r\n        ps.is_available,\r\n        ps.status_name AS status_name\r\n    FROM\r\n        products p\r\n    JOIN\r\n        product_status ps ON p.id_product_status = ps.id_product_status\r\n    WHERE\r\n        ps.is_available = true\r\n    ORDER BY\r\n        p.id_product DESC;\r\nEND;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: delete_product\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.delete_product(p_id integer)\n RETURNS void\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nBEGIN\r\n    -- Elimina el producto de la tabla 'products' donde el ID coincida.\r\n    -- Asegúrate de que la tabla se llame 'products' y la columna 'id_product'.\r\n    DELETE FROM products\r\n    WHERE id_product = p_id;\r\nEND;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_maintenance_folders\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_maintenance_folders()\n RETURNS TABLE(folder_name text)\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nBEGIN\r\n    RETURN QUERY\r\n    SELECT value1\r\n    FROM public.maintenance\r\n    WHERE name = 'Folders';\r\nEND;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_tracking_by_guia\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_tracking_by_guia(p_numero_guia text)\n RETURNS TABLE(id_tracking bigint, cliente text, producto text, nombre_tienda text, fecha_compra date, fecha_entrega_miami date)\n LANGUAGE sql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\n    SELECT\r\n        t.id_tracking,\r\n        t.cliente,\r\n        t.producto,\r\n        store.nombre_tienda,\r\n        t.fecha_compra,\r\n        t.fecha_entrega_miami\r\n    FROM tracking t\r\n    LEFT JOIN stores store ON t.id_store = store.id_store\r\n    WHERE t.codigo_seguimiento_interno = p_numero_guia\r\n       OR t.codigo_seguimiento_externo = p_numero_guia;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_all_trackings\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_all_trackings()\n RETURNS TABLE(id_tracking bigint, cliente text, producto text, nombre_tienda text, fecha_compra date, codigo_seguimiento_interno text, codigo_seguimiento_externo text, ultimo_estado text, ultima_fecha timestamp with time zone, fecha_entrega_miami date)\n LANGUAGE sql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\n    SELECT\r\n        t.id_tracking,\r\n        t.cliente,\r\n        t.producto,\r\n        s.nombre_tienda,\r\n        t.fecha_compra,\r\n        t.codigo_seguimiento_interno,\r\n        t.codigo_seguimiento_externo,\r\n        st.status_name  AS ultimo_estado,\r\n        th.fecha_hora   AS ultima_fecha,\r\n        t.fecha_entrega_miami -- Ahora coincide con la definición de arriba\r\n    FROM tracking t\r\n    LEFT JOIN stores s ON t.id_store = s.id_store\r\n    LEFT JOIN LATERAL (\r\n        SELECT th2.id_status_tracking, th2.fecha_hora\r\n        FROM tracking_historial th2\r\n        WHERE th2.id_tracking = t.id_tracking\r\n        ORDER BY th2.fecha_hora DESC\r\n        LIMIT 1\r\n    ) th ON true\r\n    LEFT JOIN status_tracking st ON th.id_status_tracking = st.id_status_tracking\r\n    WHERE th.id_status_tracking IS NULL\r\n       OR th.id_status_tracking != 9\r\n    ORDER BY t.fecha_compra DESC;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_admin_order_items\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_admin_order_items()\n RETURNS TABLE(id bigint, created_at timestamp with time zone, client_name text, client_phone text, product_name text, size text, quantity integer, price numeric, image_url text, usa_reviewed boolean, id_status bigint, status_name character varying, invoice_id bigint)\n LANGUAGE plpgsql\n SECURITY DEFINER\nAS $function$\r\nBEGIN\r\n  RETURN QUERY\r\n  SELECT\r\n    o.id,\r\n    o.created_at,\r\n    o.client_name,\r\n    o.client_phone,\r\n    o.product_name,\r\n    o.size,\r\n    o.quantity,\r\n    o.price,\r\n    o.image_url,\r\n    o.usa_reviewed,\r\n    o.id_status,\r\n    s.status_name,\r\n    o.invoice_id\r\n  FROM public.order_items o\r\n  INNER JOIN public.status s \r\n    ON o.id_status = s.id_status\r\n  ORDER BY o.created_at DESC;\r\nEND;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_maintenance_by_name_and_active\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_maintenance_by_name_and_active(search_name character varying)\n RETURNS SETOF maintenance\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$\r\nbegin\r\n  return query\r\n  select *\r\n  from public.maintenance\r\n  where name = search_name\r\n    and status_id = 1;\r\nend;\r\n$function$\n;\n"
  },
  {
    "Script SQL Completo": "-- ==========================================\n-- FUNCION / SP: get_available_products\n-- ==========================================\nCREATE OR REPLACE FUNCTION public.get_available_products()\n RETURNS TABLE(id_product integer, product_name text, category text, size text, price numeric, image_url text, is_available boolean, product_status text)\n LANGUAGE plpgsql\n SECURITY DEFINER\n SET search_path TO 'public'\nAS $function$BEGIN\r\n    RETURN QUERY\r\n    SELECT\r\n        p.id_product::integer,\r\n        p.product_name::text,\r\n        c.category_name::text,\r\n        p.size::text,\r\n        p.price::numeric,\r\n        p.image_url::text,\r\n        ps.is_available::boolean,\r\n        ps.status_name::text AS product_status\r\n    FROM\r\n        products p\r\n    JOIN\r\n        product_status ps ON p.id_product_status = ps.id_product_status\r\n    JOIN\r\n        product_category c ON p.category = c.id_category -- ◄ CORREGIDO: product_category\r\n    ORDER BY\r\n        p.id_product DESC;\r\nEND;$function$\n;\n"
  }
]